# Generated by Django 6.0.4 on 2026-04-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('species', models.CharField(max_length=260)),
                ('age', models.IntegerField()),
                ('health', models.CharField(max_length=260)),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.enclosures')),
            ],
        ),
    ]
